### ISSUE TITLE
RestError: Error sending request: Unsupported cache mode: no-store

### ISSUE THREAD

**Issue by mcm-ham** [cloudflare/workerd#2426]
Hi, I'm using Azure Communication Services to send emails. Unfortunately, their library hard codes cache no-store which I have no way to remove:
https://github.com/Azure/azure-sdk-for-js/blob/424bfd1b507ba02e1895269a91f224fd55cfddb5/sdk/core/core-rest-pipeline/src/fetchHttpClient.ts#L72

And Cloudflare Pages Function throws an error when that's set preventing the request from working:
> [ERROR] RestError: Error sending request: Unsupported cache mode: no-store You may need to enable the cache_option_enabled compatability flag.

I tried setting `compatibility_flags=["cache_option_enabled"]` in wrangler.toml without success, it just removed the suggestion from error message.

I'm just wondering is there a reason this is an error instead of a warning and just proceed with sending request?

**Comment by vicb** [comment]
This should have been fixed via https://github.com/cloudflare/workerd/pull/2434

**Comment by yoeven** [comment]
This isn't fixed. 

<img width="1177" alt="Image" src="https://github.com/user-attachments/assets/2239f8fd-6223-4aea-a090-1e2603ef533a" />

**Comment by vilenleung** [comment]
any update?
