### ISSUE TITLE
🐛 Bug Report — Runtime APIs - Unable to make https requests with query strings

### ISSUE THREAD

**Issue by MatthewSteeples** [cloudflare/workerd#5077]
Repro code

```typescript
const httpsGet = (url: string): Promise<{ statusCode?: number }> => {
	return new Promise((resolve, reject) => {
		try {
			const req = https.get(url, (res) => {
				// Consume data to allow socket to close
				res.on('data', () => {});
				res.on('end', () => resolve({ statusCode: res.statusCode }));
				res.on('error', (err) => reject(err));
			});
			req.on('error', (err) => reject(err));
		} catch (err) {
			reject(err);
		}
	});
};

const res = await httpsGet('https://www.postb.in/1757787219011-0393211871851');
const res2 = await httpsGet('https://www.postb.in/1757787219011-0393211871851?test=1');
const res3 = await httpsGet('https://www.postb.in/1757787219011-0393211871851?test=1&test2=2');
const res4 = await httpsGet('https://www.postb.in/1757787219011-0393211871851?test=1&test2=2&test3=%2bas');
```

`res` gives a 200, but the rest of them don't even attempt the request and return a 404

**Comment by MatthewSteeples** [comment]
Tagging @anonrig as you've been involved in my previous submissions in this area

**Comment by anonrig** [comment]
The URLs you've shared all returns 404. I've tested it with a different url, I couldn't reproduce. Can you validate if it still fails?

**Comment by anonrig** [comment]
Actually, I just confirmed this.

**Comment by MatthewSteeples** [comment]
Apologies, the site I was using times the URLs out after 30 minutes, but I would imagine the first 404 is legitimate while the others demonstrate the behaviour

**Comment by anonrig** [comment]
https://github.com/cloudflare/workerd/pull/5135 will fix this behavior. Apologies for the inconvenience.

**Comment by MatthewSteeples** [comment]
No problem. Happy to continue to report these and let me know if you want me to be doing anything differently.

**Comment by anonrig** [comment]
No this is perfect. Thanks!

**Comment by MatthewSteeples** [comment]
Hi @anonrig, just wanted to check to see if there was a way I could find out if this fix has been deployed as I'm still seeing this issue

**Comment by MatthewSteeples** [comment]
Hi @anonrig, sorry to chase but I was wondering if you know whether this change has been deployed yet because I'm still unable to make requests with query strings on them

**Comment by anonrig** [comment]
hey @MatthewSteeples it should have been fixed. can you share a new reproduction?

**Comment by MatthewSteeples** [comment]
I'll see if I can turn it into a minimal repro, but this is the code that's failing in my project:

```Typescript
const qs = url.searchParams.toString();
const path = "/ff1ab090-de9c-4338-9dd8-43d8226aaa6b" + (qs ? "?" + qs : "");

const result = await new Promise<string>((resolve, reject) => {
	const options: https.RequestOptions = {
		hostname: "webhook.site",
		port: 443,
		path: path,
		method: "GET",
		headers: {
			"Content-Type": "application/json"
		},
	};

	const req = https.request(options, (res) => {
		let body = "";
		res.on("data", (chunk) => (body += chunk));
		res.on("end", () => resolve(`status=${res.statusCode}; body=${body}`));
	});

	req.on("error", (err) => reject(err));
	req.end();
});
````

(echos the query string parameters that were passed in to the worker)

**Comment by MatthewSteeples** [comment]
I've just tried the original code I submitted and that still shows the issue as well. My scratchpad is actually [open on github](https://github.com/MatthewSteeples/durable-object-starter/commit/98f180c8e078f440835f45466645affe7ec6a848) if that helps at all

**Comment by anonrig** [comment]
> I've just tried the original code I submitted and that still shows the issue as well. My scratchpad is actually [open on github](https://github.com/MatthewSteeples/durable-object-starter/commit/98f180c8e078f440835f45466645affe7ec6a848) if that helps at all

Thank you for your patience @MatthewSteeples. Embarrassingly, this was a bug - https://github.com/cloudflare/workerd/pull/5329 fixes it (finally)
